### ISSUE TITLE
BUG: Clipping Wikipedia pages from iOS/iPadOS generate malformed urls

### ISSUE THREAD

**Issue by Azmoinal** [obsidianmd/obsidian-clipper#115]
**Version (please complete the following information):**
 - OS: iOS/iPadOS
 - Browser: Safari
 - Web Clipper version: 0.9.4
- Obsidian version: 1.7.4

**Describe the bug**
Trying to clip a Wikipedia page from mobile (iPhone or iPad) return a file with the correct content but image urls are malformed. They are missing of "http:" part. 

If, before clipping, the desktop version of the same page has been selected, the URLs are correct (including also the "http:" missing prefix)

**To reproduce**
1. Import kepano's template for Wikipedia from [here](https://github.com/kepano/clipper-templates/tree/main/templates)
2. Go to a Wikipedia page from a iOS/iPadOS device (e.g. https://it.wikipedia.org/wiki/Baluardo)
3  Check it is the mobile version of the page.
4. Clip the page selecting the Wikipedia template
5. Go to the page and verify that links to images are broken (i.e. they are like that //upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Bastion.rempare.png/220px-Bastion.rempare.png)

If, in step 3, instead to use the mobile version you select "show desktop version" subsequent steps return the correct import (i.e. the links are http://upload...)

Indeed importing Wikipedia pages into obsidian using clipper works fine on my MacBook or windows laptop.

**Expected behavior**
I would have the same behavior using desktop and mobile version of the same Wikipedia page, so the import should ends producing a markdown file  with the correct external URLs (including images included into the text).

**Your template file**
Below the template I'm using. I tried to reimport the original from kepano's GitHub project obtaining the same results.

```
{
  "schemaVersion": "0.1.0",
  "name": "Wikipedia",
  "behavior": "create",
  "noteContentFormat": "{{selectorHtml:#mw-content-text|remove_html:(\".navbox,.printfooter,.side-box\")|markdown}}",
  "properties": [
    {
      "name": "title",
      "value": "{{title}}",
      "type": "text"
    },
    {
      "name": "source",
      "value": "{{url}}",
      "type": "text"
    },
    {
      "name": "author",
      "value": "{{author|split:\\\", \\\"|wikilink|join}}",
      "type": "multitext"
    },
    {
      "name": "published",
      "value": "{{published}}",
      "type": "date"
    },
    {
      "name": "created",
      "value": "{{date}}",
      "type": "date"
    },
    {
      "name": "description",
      "value": "{{description}}",
      "type": "text"
    },
    {
      "name": "tags",
      "value": "clippings",
      "type": "multitext"
    }
  ],
  "triggers": [
    "Https://*wikipedia*"
  ],
  "noteNameFormat": "{{title}}",
  "path": "Appunti/Estratti Web"
}
```

**Comment by kepano** [comment]
Should be fixed in 0.9.5

**Comment by Azmoinal** [comment]
The issue is still here with 0.10.0.

For instance clipping the following page for iOS leads to the same "//upload" wrong links.

https://it.m.wikipedia.org/wiki/Petrolio

**Comment by kepano** [comment]
I believe this is fixed, if not it should be reopened on the defuddle repo
