### ISSUE TITLE
BUG: Web Clipper doesn't insert image URL

### ISSUE THREAD

**Issue by Smitty010** [obsidianmd/obsidian-clipper#388]
**Version (please complete the following information):**

- OS: [e.g. Windows] Windows 11
- Browser [e.g. Chrome, Firefox] Chrome
- Web Clipper version: [e.g. 0.9.5] .10.9
- Obsidian version: [e.g. 1.7.5] 1.8.9

**Describe the bug**

If I clip the following article, there are no images.  I don't think their iframes (but not 100% sure).
https://medium.com/@mns.nicholas/boost-your-note-taking-efficiency-automate-templates-in-obsidian-4e1d12abb9ff

**Expected behavior**

I thought that there would be links to the images

**URLs where the bug occurs**

See URL above

**To reproduce**

1. paste url into chrome
2. Click on the "rock" to get the article
3. Note that there are no images in the article.

**Your template file**

If you are using a custom template (i.e. not the Default template). Go to Web Clipper settings and click **More** → **Copy as JSON**. Paste the JSON code below.

```json
{
  "general_settings": {
    "betaFeatures": false,
    "legacyMode": false,
    "showMoreActionsButton": false,
    "silentOpen": true
  },
  "highlighter_settings": {
    "alwaysShowHighlights": true,
    "highlightBehavior": "highlight-inline",
    "highlighterEnabled": true
  },
  "interpreter_settings": {
    "defaultPromptContext": "",
    "interpreterAutoRun": false,
    "interpreterEnabled": false,
    "interpreterModel": "",
    "models": [],
    "providers": []
  },
  "migrationVersion": 1,
  "property_types": [
    {
      "defaultValue": "{{title}}",
      "name": "title",
      "type": "text"
    },
    {
      "defaultValue": "{{url}}",
      "name": "source",
      "type": "text"
    },
    {
      "defaultValue": "{{author|split:\", \"|wikilink|join}}",
      "name": "author",
      "type": "multitext"
    },
    {
      "defaultValue": "{{published}}",
      "name": "published",
      "type": "date"
    },
    {
      "defaultValue": "{{date}}",
      "name": "created",
      "type": "date"
    },
    {
      "defaultValue": "{{description}}",
      "name": "description",
      "type": "text"
    },
    {
      "defaultValue": "clippings",
      "name": "tags",
      "type": "multitext"
    },
    {
      "name": "authors",
      "type": "text"
    },
    {
      "name": "topics",
      "type": "text"
    },
    {
      "name": "type",
      "type": "text"
    },
    {
      "name": "fileclass",
      "type": "text"
    },
    {
      "name": "priority",
      "type": "text"
    },
    {
      "name": "url",
      "type": "text"
    },
    {
      "name": "updated",
      "type": "text"
    },
    {
      "name": "rating",
      "type": "text"
    },
    {
      "name": "effort",
      "type": "text"
    },
    {
      "name": "aliases",
      "type": "text"
    },
    {
      "name": "status",
      "type": "text"
    }
  ],
  "stats": {
    "addToObsidian": 69,
    "copyToClipboard": 0,
    "saveFile": 0,
    "share": 0
  },
  "template_1728146034072yt43xrhma": {
    "id": "1728146034072yt43xrhma",
    "name": "Default",
    "behavior": "create",
    "noteNameFormat": "{{title}}",
    "path": "Clippings",
    "noteContentFormat": "{{content}}\n",
    "context": "",
    "properties": [
      {
        "id": "1728146034072qsg61ak67",
        "name": "title",
        "value": "{{title}}",
        "type": "text"
      },
      {
        "id": "1728146034072z9uereuxo",
        "name": "authors",
        "value": "[{{author|split:\\\", \\\"|wikilink|join}}]",
        "type": "multitext"
      },
      {
        "id": "1741040388572pkzbwlw1x",
        "name": "topics",
        "value": "[]",
        "type": "text"
      },
      {
        "id": "1741040770354cmpdqqmlw",
        "name": "type",
        "value": "article",
        "type": "text"
      },
      {
        "id": "1741040786181s4s50xiho",
        "name": "fileclass",
        "value": "article",
        "type": "text"
      },
      {
        "id": "1741040820397sb3apcsiw",
        "name": "priority",
        "value": "",
        "type": "text"
      },
      {
        "id": "1728146034072paceo7ove",
        "name": "url",
        "value": "{{url}}",
        "type": "text"
      },
      {
        "id": "1728146034072r6u0lhawi",
        "name": "created",
        "value": "{{date}}",
        "type": "date"
      },
      {
        "id": "1741040674871ij0ht8bjy",
        "name": "updated",
        "value": "{{date}}",
        "type": "text"
      },
      {
        "id": "172814603407271x3uvp3k",
        "name": "published",
        "value": "{{published}}",
        "type": "date"
      },
      {
        "id": "17281460340729kitcb2g2",
        "name": "description",
        "value": "{{description}}",
        "type": "text"
      },
      {
        "id": "1728146034072lqma019np",
        "name": "tags",
        "value": "clippings",
        "type": "multitext"
      },
      {
        "id": "1741040880012cbexf3vrp",
        "name": "rating",
        "value": "",
        "type": "text"
      },
      {
        "id": "1741040895261f6tyicsql",
        "name": "effort",
        "value": "",
        "type": "text"
      },
      {
        "id": "1741040902407btp7cf7bm",
        "name": "aliases",
        "value": "",
        "type": "text"
      },
      {
        "id": "17410409152408n9tlmd8q",
        "name": "status",
        "value": "unprocessed",
        "type": "text"
      }
    ],
    "triggers": []
  },
  "template_17281460408645y3rjy0kw": {
    "id": "17281460408645y3rjy0kw",
    "name": "Obsidian Article",
    "behavior": "create",
    "noteNameFormat": "{{title}}",
    "path": "Clippings",
    "noteContentFormat": "[[inbox]]\n[[{{date|date:\"YYYY-MM-DD\"}}]]\n# {{title}}\nby {{author|split:\", \"|wikilink|join}}\nSaved: {{date|date:\"YYYY-MM-DD\"}}\nStatus: `INPUT[inlineSelect(option(unprocessed, not started), option(ondeck, on deck), option(inprogress, in progress), option(finished), option(abandoned, forget about it)):status]`  Priority: `INPUT[inlineSelect(option(🔽, Low),option(⏺️, Normal),option(🔼, High),option(⏫, Very High),option(🚩, Urgent), defaultValue(⏺️)):Priority]`  Rating: `INPUT[inlineSelect(option(⭐⭐⭐⭐⭐),option(⭐⭐⭐⭐),option(⭐⭐⭐),option(⭐⭐),option(⭐), defaultValue(\\\"\\\")):rating]`\n{{content}}\n## Key Ideas\n%% A way to add key ideas is to do block references (or transcluded block references) back into the Notes above %%\n\n## Next steps\n%% What are the next steps for using this information?  What other notes should this note be linked to?%%\n\nStatus: `INPUT[inlineSelect(option(unprocessed, not started), option(ondeck, on deck), option(inprogress, in progress), option(finished), option(abandoned, forget about it)):status]`  Priority: `INPUT[inlineSelect(option(🔽, Low),option(⏺️, Normal),option(🔼, High),option(⏫, Very High),option(🚩, Urgent), defaultValue(⏺️)):Priority]`  Rating: `INPUT[inlineSelect(option(⭐⭐⭐⭐⭐),option(⭐⭐⭐⭐),option(⭐⭐⭐),option(⭐⭐),option(⭐), defaultValue(\\\"\\\")):rating]`\n\n\n## Final Processing\n1. Add rating\n2. Add Key Ideas\n3. Define \\\"Next steps\\\"\n4. Change status to \\\"finished\\\"\n",
    "properties": [
      {
        "id": "1728146034072qsg61ak67",
        "name": "title",
        "value": "{{title}}",
        "type": "text"
      },
      {
        "id": "1728146034072z9uereuxo",
        "name": "authors",
        "value": "{{author|split:\\\", \\\"|wikilink|join}}",
        "type": "text"
      },
      {
        "id": "1741040388572pkzbwlw1x",
        "name": "topics",
        "value": "",
        "type": "text"
      },
      {
        "id": "17281460340729kitcb2g2",
        "name": "description",
        "value": "{{description}}",
        "type": "text"
      },
      {
        "id": "1741040770354cmpdqqmlw",
        "name": "type",
        "value": "article",
        "type": "text"
      },
      {
        "id": "1741040786181s4s50xiho",
        "name": "fileclass",
        "value": "article",
        "type": "text"
      },
      {
        "id": "1741040820397sb3apcsiw",
        "name": "priority",
        "value": "",
        "type": "text"
      },
      {
        "id": "1728146034072paceo7ove",
        "name": "url",
        "value": "{{url}}",
        "type": "text"
      },
      {
        "id": "1728146034072r6u0lhawi",
        "name": "created",
        "value": "{{date|date:\\\"YYYY-MM-DD\\\"}}",
        "type": "date"
      },
      {
        "id": "1741040674871ij0ht8bjy",
        "name": "updated",
        "value": "{{date|date:\\\"YYYY-MM-DD\\\"}}",
        "type": "text"
      },
      {
        "id": "172814603407271x3uvp3k",
        "name": "published",
        "value": "{{schema:datePublished|date:\\\"YYYY-MM-DD\\\"}}",
        "type": "date"
      },
      {
        "id": "1741040880012cbexf3vrp",
        "name": "rating",
        "value": "",
        "type": "text"
      },
      {
        "id": "1741040895261f6tyicsql",
        "name": "effort",
        "value": "",
        "type": "text"
      },
      {
        "id": "1741040902407btp7cf7bm",
        "name": "aliases",
        "value": "",
        "type": "text"
      },
      {
        "id": "17410409152408n9tlmd8q",
        "name": "status",
        "value": "unprocessed",
        "type": "text"
      },
      {
        "id": "1728146034072lqma019np",
        "name": "tags",
        "value": "clippings",
        "type": "multitext"
      }
    ],
    "triggers": [],
    "context": ""
  },
  "template_list": [
    "17281460408645y3rjy0kw",
    "1728146034072yt43xrhma"
  ],
  "vaults": []
}
```

**Comment by kepano** [comment]
I can't see the full article but I believe this should be fixed in the next version

**Comment by Smitty010** [comment]
I hope the fix includes gif's.  This url: https://medium.com/obsidian-observer/demystifying-obsidians-outlining-superpowers-20c077793356 got some images, but not others.  It didn't get any of the gif's

**Comment by Smitty010** [comment]
This is still happening with the 0.11.2 version.  Here are some urls:
https://generativeai.pub/5-tools-i-use-to-build-revenue-generating-ai-web-apps-edce82ce719e
https://medium.com/technology-hits/customize-your-vault-like-a-pro-file-explorer-and-modal-windows-3c33aa6b25a1 (no gifs)
