### ISSUE TITLE
BUG: Only the first image loads once clipped.

### ISSUE THREAD

**Issue by exmateriae** [obsidianmd/obsidian-clipper#450]
**Version (please complete the following information):**

- OS: Windows 11
- Browser Chrome 135
- Web Clipper version: 0.11.4
- Obsidian version: 1.8.9

**Describe the bug**
I have clipped long content with many images from a substack. The first image loads correctly but the next ones do not. Here is an example where two images follow each other:

![Image](https://github.com/user-attachments/assets/c7264e23-9268-4984-a167-1fe962b45b89)

I have tried copy pasting the same content in a new note and it worked, everything was loading just fine.

**Expected behavior**
I would have expected for the images to load.

**URLs where the bug occurs**
https://thezvi.substack.com/p/fertility-roundup-4

**To reproduce**
I clipped as usual, no selection was made, the clipper selected by itself the whole content and I clipped it.

**Your template file**
Default template

**Comment by kepano** [comment]
This is fixed in 0.11.7

**Comment by exmateriae** [comment]
> This is fixed in 0.11.7

Still not working for me sadly...

![Image](https://github.com/user-attachments/assets/f7dca843-762e-445f-ad81-fe06bcf2060d)

**Comment by SoapClancy** [comment]
I have the same issue. My version:
OS: MacOS 15.5
Browser: Safari 18.5
Web Clipper version: 0.11.8
Obsidian version: 1.8.10 (Installer version: 1.8.4)

**Comment by sandrop** [comment]
This is still happening for me.

CDN loading images with problematic (to obsidian clipper) URL query string paramaters

Gets truncated at the first !:

Example

On source page:
`https://substackcdn.com/image/fetch/$s_!P25e!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3ac8c091-5c6e-43e1-82cc-883ea99ccde6_1024x1024.png`

In Obsidian:
`![](https://substackcdn.com/image/fetch/$s_!P25e!)`

**Comment by shminge** [comment]
Happening for me too. I've only really noticed it being an issue with Substack, I think @sandrop 's explanation is correct (trimming at the first !)

**Comment by michellaevens** [comment]
I have the same issue on all substack.com pages. I tried TamperMonkey to change the HTML, but I couldn't write the script. Some RegEx could work I guess

**Comment by shminge** [comment]
Opened a PR to fix this issue: https://github.com/obsidianmd/obsidian-clipper/pull/547#issue-3246102958

Looking into it, it was not a trimming issue, rather an issue with how substack (and others) store images: using a srcset that effectively contains several images, and then updating the src when the page is loaded to pick one. The clipper is reading the un-updated src currently, and this PR fixes that.

**Comment by exmateriae** [comment]
Once this is resolved, does anyone have an idea how to "merge" the previous clip with this one? There are many on which I made notes and callouts and some are huge files so not viable to do by hand.

Only thing I see is asking AI to do it? Or maybe ask it to write a program to automate the modification of the previous unworking links but I'm not sure how doable this would be?
If I'm missing an obvious solution, please share! :)

**Comment by shminge** [comment]
@exmateriae you could always load both up in an online merge editor and pick which parts of each you'd like (assuming your files aren't on git already)

**Comment by exmateriae** [comment]
@shminge thanks for the very fast answer and the suggestion, I'll try that! Do you think this will be soon solved btw?:)

**Comment by shminge** [comment]
my fix was merged this morning (#547), so this should be fixed upon updating to 0.11.9 (also released this morning). I don't know what the timeline is like for extension stores to get the update, but if you're installing from here on GitHub directly it should be fixed :)

Let me know if you have any problems with it, but I really hope I've squashed this bug

**Comment by exmateriae** [comment]
> my fix was merged this morning ([#547](https://github.com/obsidianmd/obsidian-clipper/pull/547)), so this should be fixed upon updating to 0.11.9 (also released this morning). I don't know what the timeline is like for extension stores to get the update, but if you're installing from here on GitHub directly it should be fixed :)
> 
> Let me know if you have any problems with it, but I really hope I've squashed this bug

Wow funny that I asked just now haha, I manually installed and tried it and all seems to work fine now, thank you very much, this was a big issue for me!
